#!/usr/bin/env python3
"""Generate raw SVG files and src/raw.ts from art.py.

Run from the repo root:  pnpm icons:generate   (python3 packages/icons/scripts/generate.py)
Every id inside a graphic is prefixed with __P__; the React components replace it with a
per-instance useId() value so many copies can live on one page without gradient clashes.
"""
import json, pathlib, re, sys
HERE = pathlib.Path(__file__).parent
sys.path.insert(0, str(HERE))
import art  # noqa: E402

PKG = HERE.parent
P = "__P__"
BODIES = {
    "blue": ("#BFE0FF", "#4C9BFF", "#1F4FD1"),
    "black": ("#5A5A64", "#1C1C21", "#050506"),
    "silver": ("#FFFFFF", "#E7EBF1", "#9AA5B4"),
}
ICONS = {  # export name -> art.ico kind
    "bubbles": "wash", "vacuum": "vacuum", "sparkle": "detail", "tyre": "tyre", "drop": "drop",
    "car": "car", "chat": "chat", "shield": "shield", "check": "check", "coin": "coin",
}

def split(svg):
    m = re.match(r'<svg ([^>]*)>(.*)</svg>$', svg, re.S)
    vb = re.search(r'viewBox="([^"]+)"', m.group(1)).group(1)
    return vb, m.group(2)

raw = {}
for name, kind in ICONS.items():
    vb, inner = split(art.ico(kind, 64, P))
    raw[name] = {"viewBox": vb, "markup": inner}
for body, cols in BODIES.items():
    vb, inner = split(art.car(P, body=cols, w=400))
    raw[f"car-{body}"] = {"viewBox": vb, "markup": inner}
# a single soap bubble, useful as decoration
vb = "0 0 40 40"
raw["bubble"] = {"viewBox": vb, "markup": re.sub(r'</defs>.*', '</defs>', art.defs(P), flags=re.S) + art.bubble(20, 20, 18, P)}

ts = ["// Generated by scripts/generate.py from scripts/art.py. Do not edit by hand.",
      "export interface RawGraphic { viewBox: string; markup: string }",
      "export type GraphicName = " + " | ".join(json.dumps(k) for k in raw) + ";",
      "export const RAW: Record<GraphicName, RawGraphic> = {"]
for k, v in raw.items():
    ts.append(f"  {json.dumps(k)}: {{ viewBox: {json.dumps(v['viewBox'])}, markup: {json.dumps(v['markup'], ensure_ascii=False)} }},")
ts.append("};")
(PKG / "src/raw.ts").write_text("\n".join(ts) + "\n")

for k, v in raw.items():
    vbw, vbh = v["viewBox"].split()[2:]
    markup = v["markup"].replace(P, f"ra-{k}-")
    (PKG / "svg" / f"{k}.svg").write_text(
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{v["viewBox"]}" width="{vbw}" height="{vbh}">{markup}</svg>\n')
print("icons: wrote", len(raw), "graphics to src/raw.ts and svg/")
